name: blogbloc
description: Blog application developed in Flutter with the BloC design pattern

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_bloc: ^4.0.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  equatable: ^1.1.1
  meta: ^1.1.8
  intl: ^0.16.1
  image_picker: ^0.6.5+3
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
